name: GitHub Activity Readme
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
jobs:
  build:
    name: Update GitHub Activity Readme
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          COMMIT_MSG: "Update recent activity"
          MAX_LINES: 10
          COMMIT_NAME: GitHub Activity Readme
